# Generated by Django 4.2.28 on 2026-02-11 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成')], default='planning', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='1=主任务, 2=子任务, 3=孙任务', verbose_name='层级')),
                ('path', models.CharField(blank=True, default='', help_text='路径枚举，如 /1/12/34', max_length=255, verbose_name='路径')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('normal_flag', models.CharField(choices=[('normal', '正常'), ('overdue', '已逾期')], default='normal', max_length=20, verbose_name='正常标识')),
                ('is_overdue_notified', models.BooleanField(default=False, verbose_name='已发送逾期提醒')),
                ('is_due_notified', models.BooleanField(default=False, verbose_name='已发送截止提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task', verbose_name='父任务')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=500, verbose_name='文件Key')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小')),
                ('url', models.URLField(verbose_name='文件URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='任务')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
                'db_table': 'task_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='字段名')),
                ('old_value', models.CharField(blank=True, default='', max_length=255, verbose_name='旧值')),
                ('new_value', models.CharField(blank=True, default='', max_length=255, verbose_name='新值')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_changes', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务变更历史',
                'verbose_name_plural': '任务变更历史',
                'db_table': 'task_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['task', 'changed_at'], name='task_histor_task_id_7a4296_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'level'], name='tasks_project_d892ca_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='tasks_assigne_972e70_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_status_031d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['end_date'], name='tasks_end_dat_78c269_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['normal_flag'], name='tasks_normal__6be3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['path'], name='tasks_path_d4bef3_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('level__in', [1, 2, 3])), name='valid_task_level'),
        ),
    ]
